name: Build snac2 Docker image and push to the registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to build container from
        required: true
        default: latest
        type: string
  

jobs:
  obtain:
    runs-on: ubuntu-latest
    steps:
      - name: Get source tarball
        run: curl -s -O https://codeberg.org/grunfink/snac2/archive/2.75.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snac-src
          path: 2.75.tar.gz
          retention-days: 1

  buildpush:
    needs: obtain

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # - name: Checkout repository
      # uses: actions/checkout@v4
      # with:
        # fetch-depth: 0
        # fetch-tags: 'true'
    # - name: Output latest tag
    # - name: Checkout selected tag
      # uses: ./.github/actions/checkout-tag
      # with:
        # tag: ${{ inputs.tag }}
    # - name: Output latest tag
      # run: echo `pwd`; echo "${{ inputs.tag }}"
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: snac-src
    - name: Extract sources
      run: |
        tar -xzf 2.75.tar.gz
        cd ./snac2
        echo `pwd`; echo `ls`
      
    - name: Login to GitHub packages registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: |
        echo `pwd`
        cd ./snac2
        docker build . --file Dockerfile --tag snac2
    - name: Push built Docker image to the registry
      run: |
        docker tag snac2 ghcr.io/${{ github.repository_owner }}/snac2:${{ inputs.tag }}
        docker push ghcr.io/${{ github.repository_owner }}/snac2:${{ inputs.tag }}
